#
#   Copyright (c) 2021, 2121, ducesoft and/or its affiliates. All rights reserved.
#   DUCESOFT PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

.PHONY: i

.PHONY: i
i:
	@flutter pub get
	@flutter build web

setup:
	yarn set version stable --proxy=http://127.0.0.1:1087
	yarn sdks base
