# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer_inner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14transfer_inner.proto\x12\x0borg.ppc.ptp\"\x1c\n\x0bPeekInbound\x12\r\n\x05topic\x18\x01 \x01(\t\",\n\nPopInbound\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x05\"\x98\x01\n\x0bPushInbound\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x38\n\x08metadata\x18\x03 \x03(\x0b\x32&.org.ppc.ptp.PushInbound.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x0eReleaseInbound\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x05\"\xb4\x01\n\x11TransportOutbound\x12>\n\x08metadata\x18\x01 \x03(\x0b\x32,.org.ppc.ptp.TransportOutbound.MetadataEntry\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa6\x02\n\x18PrivateTransferTransport\x12@\n\x04peek\x12\x18.org.ppc.ptp.PeekInbound\x1a\x1e.org.ppc.ptp.TransportOutbound\x12>\n\x03pop\x12\x17.org.ppc.ptp.PopInbound\x1a\x1e.org.ppc.ptp.TransportOutbound\x12@\n\x04push\x12\x18.org.ppc.ptp.PushInbound\x1a\x1e.org.ppc.ptp.TransportOutbound\x12\x46\n\x07release\x12\x1b.org.ppc.ptp.ReleaseInbound\x1a\x1e.org.ppc.ptp.TransportOutboundB(\n\x0bio.bfia.ptpZ\x19github.com/be-io/mesh/ptpb\x06proto3')



_PEEKINBOUND = DESCRIPTOR.message_types_by_name['PeekInbound']
_POPINBOUND = DESCRIPTOR.message_types_by_name['PopInbound']
_PUSHINBOUND = DESCRIPTOR.message_types_by_name['PushInbound']
_PUSHINBOUND_METADATAENTRY = _PUSHINBOUND.nested_types_by_name['MetadataEntry']
_RELEASEINBOUND = DESCRIPTOR.message_types_by_name['ReleaseInbound']
_TRANSPORTOUTBOUND = DESCRIPTOR.message_types_by_name['TransportOutbound']
_TRANSPORTOUTBOUND_METADATAENTRY = _TRANSPORTOUTBOUND.nested_types_by_name['MetadataEntry']
PeekInbound = _reflection.GeneratedProtocolMessageType('PeekInbound', (_message.Message,), {
  'DESCRIPTOR' : _PEEKINBOUND,
  '__module__' : 'transfer_inner_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.PeekInbound)
  })
_sym_db.RegisterMessage(PeekInbound)

PopInbound = _reflection.GeneratedProtocolMessageType('PopInbound', (_message.Message,), {
  'DESCRIPTOR' : _POPINBOUND,
  '__module__' : 'transfer_inner_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.PopInbound)
  })
_sym_db.RegisterMessage(PopInbound)

PushInbound = _reflection.GeneratedProtocolMessageType('PushInbound', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _PUSHINBOUND_METADATAENTRY,
    '__module__' : 'transfer_inner_pb2'
    # @@protoc_insertion_point(class_scope:org.ppc.ptp.PushInbound.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _PUSHINBOUND,
  '__module__' : 'transfer_inner_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.PushInbound)
  })
_sym_db.RegisterMessage(PushInbound)
_sym_db.RegisterMessage(PushInbound.MetadataEntry)

ReleaseInbound = _reflection.GeneratedProtocolMessageType('ReleaseInbound', (_message.Message,), {
  'DESCRIPTOR' : _RELEASEINBOUND,
  '__module__' : 'transfer_inner_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.ReleaseInbound)
  })
_sym_db.RegisterMessage(ReleaseInbound)

TransportOutbound = _reflection.GeneratedProtocolMessageType('TransportOutbound', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRANSPORTOUTBOUND_METADATAENTRY,
    '__module__' : 'transfer_inner_pb2'
    # @@protoc_insertion_point(class_scope:org.ppc.ptp.TransportOutbound.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _TRANSPORTOUTBOUND,
  '__module__' : 'transfer_inner_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.TransportOutbound)
  })
_sym_db.RegisterMessage(TransportOutbound)
_sym_db.RegisterMessage(TransportOutbound.MetadataEntry)

_PRIVATETRANSFERTRANSPORT = DESCRIPTOR.services_by_name['PrivateTransferTransport']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013io.bfia.ptpZ\031github.com/be-io/mesh/ptp'
  _PUSHINBOUND_METADATAENTRY._options = None
  _PUSHINBOUND_METADATAENTRY._serialized_options = b'8\001'
  _TRANSPORTOUTBOUND_METADATAENTRY._options = None
  _TRANSPORTOUTBOUND_METADATAENTRY._serialized_options = b'8\001'
  _PEEKINBOUND._serialized_start=37
  _PEEKINBOUND._serialized_end=65
  _POPINBOUND._serialized_start=67
  _POPINBOUND._serialized_end=111
  _PUSHINBOUND._serialized_start=114
  _PUSHINBOUND._serialized_end=266
  _PUSHINBOUND_METADATAENTRY._serialized_start=219
  _PUSHINBOUND_METADATAENTRY._serialized_end=266
  _RELEASEINBOUND._serialized_start=268
  _RELEASEINBOUND._serialized_end=316
  _TRANSPORTOUTBOUND._serialized_start=319
  _TRANSPORTOUTBOUND._serialized_end=499
  _TRANSPORTOUTBOUND_METADATAENTRY._serialized_start=219
  _TRANSPORTOUTBOUND_METADATAENTRY._serialized_end=266
  _PRIVATETRANSFERTRANSPORT._serialized_start=502
  _PRIVATETRANSFERTRANSPORT._serialized_end=796
# @@protoc_insertion_point(module_scope)
